### ISSUE TITLE
TypeError: data.map is not a function

### ISSUE THREAD

**Issue by rzuppur** [pipedrive/client-nodejs#408]
- Pipedrive version 18.0.1 
- Node version 16.18.1

Getting activity fields gives me this error:

```
TypeError: data.map is not a function
    at Function.convertToType ([...]\pipedrive\dist\ApiClient.js:949:25)
    at Function.constructFromObject ([...]\pipedrive\dist\model\Field.js:141:58)
    at Function.convertToType ([...]\pipedrive\dist\ApiClient.js:945:25)
    at [...]\pipedrive\dist\ApiClient.js:950:32
    at Array.map (<anonymous>)
    at Function.convertToType ([...]\pipedrive\dist\ApiClient.js:949:25)
    at Function.constructFromObject ([...]\pipedrive\dist\model\FieldsResponseAllOf.js:62:47)
    at Function.constructFromObject ([...]\pipedrive\dist\model\FieldsResponse.js:68:41)
    at Function.convertToType ([...]\pipedrive\dist\ApiClient.js:945:25)
    at ApiClient.deserialize ([...]\pipedrive\dist\ApiClient.js:391:24)
```

Example code:

```js
import Pipedrive from "pipedrive";

const api = new Pipedrive.ApiClient();
api.authentications.api_key.apiKey = "TOKEN";

// This works
const dealFieldsApi = new Pipedrive.DealFieldsApi(api);
console.log(await dealFieldsApi.getDealFields());

// This doesn't
const activityFieldsApi = new Pipedrive.ActivityFieldsApi(api);
console.log(await activityFieldsApi.getActivityFields());
```

**Comment by bashmach** [comment]
Hi @rzuppur,

Could you please confirm that issue still persists for you and can be reproduced with latest version of SDK (at the moment is ^18.1)?

If still doesn't work for you and gives an error, please try to query the [endpoint](https://developers.pipedrive.com/docs/api/v1/ActivityFields) with same api_token in Postman (or any other tool) to check what response it returns to you and let us know.

**Comment by rzuppur** [comment]
Hi, seems to be working in the latest version!
