### ISSUE TITLE
more breaking changes on version 18

### ISSUE THREAD

**Issue by sibelius** [pipedrive/client-nodejs#414]
this is breaking for me

```
TypeError: this.apiClient.callApi is not a function
at OrganizationsApi.addOrganizationWithHttpInfo (node_modules/pipedrive/dist/api/OrganizationsApi.js:87:29)
at OrganizationsApi.addOrganization (node_modules/pipedrive/dist/api/OrganizationsApi.js:100:19)
```

this is the code

```jsx
export const pipedriveGetApi = () => {
  // 18
  const defaultClient = new pipedrive.ApiClient();

  // const defaultClient = pipedrive.ApiClient.instance;

  const apiToken = defaultClient.authentications.api_key;

  apiToken.apiKey = config.PIPEDRIVE_API_TOKEN;

  return pipedrive;
};

export const pipedriveOrganizationPost = async (
  organization: OrganizationPayload,
): Promise<OrganizationResult> => {
  const defaultClient = pipedriveGetApi();

  const api = new pipedrive.OrganizationsApi(defaultClient);

  const opts = pipedrive.NewOrganization.constructFromObject({
    ...organization,
    visible_to: PIPEDRIVE_VISIBLE_TO.EVERYONE,
  });

  return await api.addOrganization(opts);
};
```

**Comment by RuTsEST** [comment]
Hey!

You're returning `pipedrive` from `pipedriveGetApi` function instead of `defaultClient`.

Hope this helps!
